// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"
)

type Materium struct {
	Idmateria    int32          `json:"idmateria"`
	Nombre       string         `json:"nombre"`
	Cuatrimestre int32          `json:"cuatrimestre"`
	Descripcion  sql.NullString `json:"descripcion"`
}

type Usuario struct {
	Idusuario int32  `json:"idusuario"`
	Nombre    string `json:"nombre"`
	Apellido  string `json:"apellido"`
}

type Voto struct {
	Idusuario       int32          `json:"idusuario"`
	Idmateria       int32          `json:"idmateria"`
	PuntuacionDif   sql.NullInt32  `json:"puntuacion_dif"`
	PuntuacionRel   sql.NullInt32  `json:"puntuacion_rel"`
	PuntuacionGusto sql.NullInt32  `json:"puntuacion_gusto"`
	Descripcion     sql.NullString `json:"descripcion"`
	FechaVoto       time.Time      `json:"fecha_voto"`
}
