// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const actualizarMateria = `-- name: ActualizarMateria :exec
UPDATE materia
SET nombre = $2, cuatrimestre = $3, descripcion = $4
WHERE idMateria = $1
`

type ActualizarMateriaParams struct {
	Idmateria    int32          `json:"idmateria"`
	Nombre       string         `json:"nombre"`
	Cuatrimestre int32          `json:"cuatrimestre"`
	Descripcion  sql.NullString `json:"descripcion"`
}

func (q *Queries) ActualizarMateria(ctx context.Context, arg ActualizarMateriaParams) error {
	_, err := q.db.ExecContext(ctx, actualizarMateria,
		arg.Idmateria,
		arg.Nombre,
		arg.Cuatrimestre,
		arg.Descripcion,
	)
	return err
}

const actualizarUsuario = `-- name: ActualizarUsuario :exec
UPDATE usuario
SET nombre = $2, 
    apellido = $3
WHERE idUsuario = $1
`

type ActualizarUsuarioParams struct {
	Idusuario int32  `json:"idusuario"`
	Nombre    string `json:"nombre"`
	Apellido  string `json:"apellido"`
}

func (q *Queries) ActualizarUsuario(ctx context.Context, arg ActualizarUsuarioParams) error {
	_, err := q.db.ExecContext(ctx, actualizarUsuario, arg.Idusuario, arg.Nombre, arg.Apellido)
	return err
}

const actualizarVoto = `-- name: ActualizarVoto :exec
UPDATE voto
SET puntuacion_dif = $3, 
    puntuacion_rel = $4, 
    puntuacion_gusto = $5, 
    descripcion = $6,
    fecha_voto= $7
WHERE idUsuario = $1 AND idMateria = $2
`

type ActualizarVotoParams struct {
	Idusuario       int32          `json:"idusuario"`
	Idmateria       int32          `json:"idmateria"`
	PuntuacionDif   sql.NullInt32  `json:"puntuacion_dif"`
	PuntuacionRel   sql.NullInt32  `json:"puntuacion_rel"`
	PuntuacionGusto sql.NullInt32  `json:"puntuacion_gusto"`
	Descripcion     sql.NullString `json:"descripcion"`
	FechaVoto       time.Time      `json:"fecha_voto"`
}

func (q *Queries) ActualizarVoto(ctx context.Context, arg ActualizarVotoParams) error {
	_, err := q.db.ExecContext(ctx, actualizarVoto,
		arg.Idusuario,
		arg.Idmateria,
		arg.PuntuacionDif,
		arg.PuntuacionRel,
		arg.PuntuacionGusto,
		arg.Descripcion,
		arg.FechaVoto,
	)
	return err
}

const deleteMateria = `-- name: DeleteMateria :exec
DELETE FROM materia 
WHERE idMateria = $1
`

func (q *Queries) DeleteMateria(ctx context.Context, idmateria int32) error {
	_, err := q.db.ExecContext(ctx, deleteMateria, idmateria)
	return err
}

const deleteUsuario = `-- name: DeleteUsuario :exec
DELETE FROM usuario 
WHERE idUsuario = $1
`

func (q *Queries) DeleteUsuario(ctx context.Context, idusuario int32) error {
	_, err := q.db.ExecContext(ctx, deleteUsuario, idusuario)
	return err
}

const deleteVoto = `-- name: DeleteVoto :exec
DELETE FROM voto
WHERE idUsuario = $1 AND idMateria = $2
`

type DeleteVotoParams struct {
	Idusuario int32 `json:"idusuario"`
	Idmateria int32 `json:"idmateria"`
}

func (q *Queries) DeleteVoto(ctx context.Context, arg DeleteVotoParams) error {
	_, err := q.db.ExecContext(ctx, deleteVoto, arg.Idusuario, arg.Idmateria)
	return err
}

const getMateria = `-- name: GetMateria :one
SELECT idMateria, nombre, cuatrimestre, descripcion
FROM materia
WHERE idMateria = $1
`

func (q *Queries) GetMateria(ctx context.Context, idmateria int32) (Materium, error) {
	row := q.db.QueryRowContext(ctx, getMateria, idmateria)
	var i Materium
	err := row.Scan(
		&i.Idmateria,
		&i.Nombre,
		&i.Cuatrimestre,
		&i.Descripcion,
	)
	return i, err
}

const getUsuario = `-- name: GetUsuario :one
SELECT idUsuario, nombre, apellido
FROM usuario
WHERE idUsuario = $1
`

func (q *Queries) GetUsuario(ctx context.Context, idusuario int32) (Usuario, error) {
	row := q.db.QueryRowContext(ctx, getUsuario, idusuario)
	var i Usuario
	err := row.Scan(&i.Idusuario, &i.Nombre, &i.Apellido)
	return i, err
}

const getVoto = `-- name: GetVoto :one
SELECT idUsuario, idMateria, puntuacion_dif, puntuacion_rel, puntuacion_gusto, descripcion,fecha_voto
FROM voto
WHERE idUsuario = $1 AND idMateria = $2
`

type GetVotoParams struct {
	Idusuario int32 `json:"idusuario"`
	Idmateria int32 `json:"idmateria"`
}

func (q *Queries) GetVoto(ctx context.Context, arg GetVotoParams) (Voto, error) {
	row := q.db.QueryRowContext(ctx, getVoto, arg.Idusuario, arg.Idmateria)
	var i Voto
	err := row.Scan(
		&i.Idusuario,
		&i.Idmateria,
		&i.PuntuacionDif,
		&i.PuntuacionRel,
		&i.PuntuacionGusto,
		&i.Descripcion,
		&i.FechaVoto,
	)
	return i, err
}

const insertarMateria = `-- name: InsertarMateria :one
INSERT INTO materia (idMateria, nombre, cuatrimestre, descripcion)
VALUES ($1, $2, $3, $4)
RETURNING idMateria, nombre, cuatrimestre, descripcion
`

type InsertarMateriaParams struct {
	Idmateria    int32          `json:"idmateria"`
	Nombre       string         `json:"nombre"`
	Cuatrimestre int32          `json:"cuatrimestre"`
	Descripcion  sql.NullString `json:"descripcion"`
}

func (q *Queries) InsertarMateria(ctx context.Context, arg InsertarMateriaParams) (Materium, error) {
	row := q.db.QueryRowContext(ctx, insertarMateria,
		arg.Idmateria,
		arg.Nombre,
		arg.Cuatrimestre,
		arg.Descripcion,
	)
	var i Materium
	err := row.Scan(
		&i.Idmateria,
		&i.Nombre,
		&i.Cuatrimestre,
		&i.Descripcion,
	)
	return i, err
}

const insertarUsuario = `-- name: InsertarUsuario :one
INSERT INTO usuario (idUsuario, nombre, apellido)
VALUES ($1, $2, $3)
RETURNING idUsuario, nombre, apellido
`

type InsertarUsuarioParams struct {
	Idusuario int32  `json:"idusuario"`
	Nombre    string `json:"nombre"`
	Apellido  string `json:"apellido"`
}

func (q *Queries) InsertarUsuario(ctx context.Context, arg InsertarUsuarioParams) (Usuario, error) {
	row := q.db.QueryRowContext(ctx, insertarUsuario, arg.Idusuario, arg.Nombre, arg.Apellido)
	var i Usuario
	err := row.Scan(&i.Idusuario, &i.Nombre, &i.Apellido)
	return i, err
}

const insertarVoto = `-- name: InsertarVoto :exec
INSERT INTO voto (idUsuario, idMateria, puntuacion_dif, puntuacion_rel, puntuacion_gusto, descripcion,fecha_voto)
VALUES ($1, $2, $3, $4, $5, $6,$7)
`

type InsertarVotoParams struct {
	Idusuario       int32          `json:"idusuario"`
	Idmateria       int32          `json:"idmateria"`
	PuntuacionDif   sql.NullInt32  `json:"puntuacion_dif"`
	PuntuacionRel   sql.NullInt32  `json:"puntuacion_rel"`
	PuntuacionGusto sql.NullInt32  `json:"puntuacion_gusto"`
	Descripcion     sql.NullString `json:"descripcion"`
	FechaVoto       time.Time      `json:"fecha_voto"`
}

func (q *Queries) InsertarVoto(ctx context.Context, arg InsertarVotoParams) error {
	_, err := q.db.ExecContext(ctx, insertarVoto,
		arg.Idusuario,
		arg.Idmateria,
		arg.PuntuacionDif,
		arg.PuntuacionRel,
		arg.PuntuacionGusto,
		arg.Descripcion,
		arg.FechaVoto,
	)
	return err
}

const listarMaterias = `-- name: ListarMaterias :many
SELECT idMateria, nombre, cuatrimestre, descripcion
FROM materia
ORDER BY cuatrimestre, nombre
`

func (q *Queries) ListarMaterias(ctx context.Context) ([]Materium, error) {
	rows, err := q.db.QueryContext(ctx, listarMaterias)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Materium
	for rows.Next() {
		var i Materium
		if err := rows.Scan(
			&i.Idmateria,
			&i.Nombre,
			&i.Cuatrimestre,
			&i.Descripcion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarUsuarios = `-- name: ListarUsuarios :many
SELECT idUsuario, nombre, apellido
FROM usuario
ORDER BY apellido, nombre
`

func (q *Queries) ListarUsuarios(ctx context.Context) ([]Usuario, error) {
	rows, err := q.db.QueryContext(ctx, listarUsuarios)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Usuario
	for rows.Next() {
		var i Usuario
		if err := rows.Scan(&i.Idusuario, &i.Nombre, &i.Apellido); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarVotosPorMateria = `-- name: ListarVotosPorMateria :many
SELECT idUsuario, idMateria, puntuacion_dif, puntuacion_rel, puntuacion_gusto, descripcion,fecha_voto
FROM voto
WHERE idMateria = $1
`

func (q *Queries) ListarVotosPorMateria(ctx context.Context, idmateria int32) ([]Voto, error) {
	rows, err := q.db.QueryContext(ctx, listarVotosPorMateria, idmateria)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Voto
	for rows.Next() {
		var i Voto
		if err := rows.Scan(
			&i.Idusuario,
			&i.Idmateria,
			&i.PuntuacionDif,
			&i.PuntuacionRel,
			&i.PuntuacionGusto,
			&i.Descripcion,
			&i.FechaVoto,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarVotosPorUsuario = `-- name: ListarVotosPorUsuario :many
SELECT idUsuario, idMateria, puntuacion_dif, puntuacion_rel, puntuacion_gusto, descripcion,fecha_voto
FROM voto
WHERE idUsuario = $1
`

func (q *Queries) ListarVotosPorUsuario(ctx context.Context, idusuario int32) ([]Voto, error) {
	rows, err := q.db.QueryContext(ctx, listarVotosPorUsuario, idusuario)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Voto
	for rows.Next() {
		var i Voto
		if err := rows.Scan(
			&i.Idusuario,
			&i.Idmateria,
			&i.PuntuacionDif,
			&i.PuntuacionRel,
			&i.PuntuacionGusto,
			&i.Descripcion,
			&i.FechaVoto,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
